//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nabavki.ArtikliWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArtikliWebService.ArtikliWSSoap")]
    public interface ArtikliWSSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Nabavki.ArtikliWebService.HelloWorldResponse HelloWorld(Nabavki.ArtikliWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Nabavki.ArtikliWebService.HelloWorldResponse> HelloWorldAsync(Nabavki.ArtikliWebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name naziv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnArtiklId", ReplyAction="*")]
        Nabavki.ArtikliWebService.ReturnArtiklIdResponse ReturnArtiklId(Nabavki.ArtikliWebService.ReturnArtiklIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnArtiklId", ReplyAction="*")]
        System.Threading.Tasks.Task<Nabavki.ArtikliWebService.ReturnArtiklIdResponse> ReturnArtiklIdAsync(Nabavki.ArtikliWebService.ReturnArtiklIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Nabavki.ArtikliWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Nabavki.ArtikliWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nabavki.ArtikliWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Nabavki.ArtikliWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnArtiklIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnArtiklId", Namespace="http://tempuri.org/", Order=0)]
        public Nabavki.ArtikliWebService.ReturnArtiklIdRequestBody Body;
        
        public ReturnArtiklIdRequest() {
        }
        
        public ReturnArtiklIdRequest(Nabavki.ArtikliWebService.ReturnArtiklIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnArtiklIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string naziv;
        
        public ReturnArtiklIdRequestBody() {
        }
        
        public ReturnArtiklIdRequestBody(string naziv) {
            this.naziv = naziv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnArtiklIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnArtiklIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nabavki.ArtikliWebService.ReturnArtiklIdResponseBody Body;
        
        public ReturnArtiklIdResponse() {
        }
        
        public ReturnArtiklIdResponse(Nabavki.ArtikliWebService.ReturnArtiklIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnArtiklIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ReturnArtiklIdResult;
        
        public ReturnArtiklIdResponseBody() {
        }
        
        public ReturnArtiklIdResponseBody(int ReturnArtiklIdResult) {
            this.ReturnArtiklIdResult = ReturnArtiklIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArtikliWSSoapChannel : Nabavki.ArtikliWebService.ArtikliWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtikliWSSoapClient : System.ServiceModel.ClientBase<Nabavki.ArtikliWebService.ArtikliWSSoap>, Nabavki.ArtikliWebService.ArtikliWSSoap {
        
        public ArtikliWSSoapClient() {
        }
        
        public ArtikliWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtikliWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtikliWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtikliWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nabavki.ArtikliWebService.HelloWorldResponse Nabavki.ArtikliWebService.ArtikliWSSoap.HelloWorld(Nabavki.ArtikliWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Nabavki.ArtikliWebService.HelloWorldRequest inValue = new Nabavki.ArtikliWebService.HelloWorldRequest();
            inValue.Body = new Nabavki.ArtikliWebService.HelloWorldRequestBody();
            Nabavki.ArtikliWebService.HelloWorldResponse retVal = ((Nabavki.ArtikliWebService.ArtikliWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nabavki.ArtikliWebService.HelloWorldResponse> Nabavki.ArtikliWebService.ArtikliWSSoap.HelloWorldAsync(Nabavki.ArtikliWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nabavki.ArtikliWebService.HelloWorldResponse> HelloWorldAsync() {
            Nabavki.ArtikliWebService.HelloWorldRequest inValue = new Nabavki.ArtikliWebService.HelloWorldRequest();
            inValue.Body = new Nabavki.ArtikliWebService.HelloWorldRequestBody();
            return ((Nabavki.ArtikliWebService.ArtikliWSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nabavki.ArtikliWebService.ReturnArtiklIdResponse Nabavki.ArtikliWebService.ArtikliWSSoap.ReturnArtiklId(Nabavki.ArtikliWebService.ReturnArtiklIdRequest request) {
            return base.Channel.ReturnArtiklId(request);
        }
        
        public int ReturnArtiklId(string naziv) {
            Nabavki.ArtikliWebService.ReturnArtiklIdRequest inValue = new Nabavki.ArtikliWebService.ReturnArtiklIdRequest();
            inValue.Body = new Nabavki.ArtikliWebService.ReturnArtiklIdRequestBody();
            inValue.Body.naziv = naziv;
            Nabavki.ArtikliWebService.ReturnArtiklIdResponse retVal = ((Nabavki.ArtikliWebService.ArtikliWSSoap)(this)).ReturnArtiklId(inValue);
            return retVal.Body.ReturnArtiklIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nabavki.ArtikliWebService.ReturnArtiklIdResponse> Nabavki.ArtikliWebService.ArtikliWSSoap.ReturnArtiklIdAsync(Nabavki.ArtikliWebService.ReturnArtiklIdRequest request) {
            return base.Channel.ReturnArtiklIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nabavki.ArtikliWebService.ReturnArtiklIdResponse> ReturnArtiklIdAsync(string naziv) {
            Nabavki.ArtikliWebService.ReturnArtiklIdRequest inValue = new Nabavki.ArtikliWebService.ReturnArtiklIdRequest();
            inValue.Body = new Nabavki.ArtikliWebService.ReturnArtiklIdRequestBody();
            inValue.Body.naziv = naziv;
            return ((Nabavki.ArtikliWebService.ArtikliWSSoap)(this)).ReturnArtiklIdAsync(inValue);
        }
    }
}
